name: Node CI app

on:
  push:
    branches:  
      - main
      - infra
  pull_request:
    branches: 
      - main
      - infra

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js 20_x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm
    - name: Install Next-JS
      run: npm i next
    - name: Build with NPM
      run: npm --prefix public/my-app/ run build 
