name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js 20_x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm --prefix public/my-app/package.json ci
    - run: npm --prefix public/my-app/package.json run build --if-present
    - run: npm --prefix public/my-app/package.json test 
