name: Node CI app

on:
  push:
    branches:  
      - main
      - infra
  pull_request:
    branches: 
      - main
      - infra

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js 20_x
      run: sudo apt-get install curl -y && \ sudo curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash - && \ sudo apt-get install -y nodejs 
    - name: Build with NPM
      run: npm --prefix public/my-app/ run build 
