name: Java CI with Maven

on:
  push:
    branches:
      - main
      - infra
  pull_request:
    branches: 
      - main
      - infra

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4 
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file api/pom.xml

